### ISSUE TITLE
NoSuchFileExpection looking for jakarta jars

### ISSUE THREAD

**Issue by zanettea** [spring-projects-experimental/spring-graal-native#120]
I received the above exception trying to compile samples (both 0.6.1 and 0.7.0). Please see the full log file 
[output.txt](https://github.com/spring-projects-experimental/spring-graal-native/files/4582899/output.txt)

**Comment by aclement** [comment]
I've seen this a few times. But I can't for the life of me remember how I worked past it each time.  It is more like a issue with the scripts than native-image. Two invalid jars end up on the classpath (from your output.txt):
```
Warning: Invalid classpath entry: /home/user/spring-graal-native/spring-graal-native-samples/spring-petclinic-jpa/target/native-image/BOOT-INF/lib/jakarta.xml.bind-api-2.3.2.jar
Warning: Invalid classpath entry: /home/user/spring-graal-native/spring-graal-native-samples/spring-petclinic-jpa/target/native-image/BOOT-INF/lib/jakarta.activation-api-1.2.1.jar
```
and then later there are issues. I'm at least going to turn down the fatal error to a warning, but I don't  quite recall why the find command in the script is finding things that aren't there to put on the classpath.

**Comment by wilkinsona** [comment]
`Class-Path` entries in jar manifests, perhaps? From time-to-time, we see similar oddities when using DevTools with certain dependencies that have "broken" manifests.

**Comment by aclement** [comment]
I wondered that Andy - but the script was doing just a unix find to create the classpath. Anyway, missing jars isn't a big deal but things crashing because of it is a problem. I've made the changes in master to just move on when a jar isn't around. If you try master it should behave better now - master is designed to work with the most recent Graal 20.1 dev builds - which you can grab here: https://github.com/graalvm/graalvm-ce-dev-builds/releases (below the 20.2 builds). It may still work with 20.0 release, I'm just not 100% sure.
