### ISSUE TITLE
Provide metrics as CSV

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#32]
As a follow-up of #30, we should generate a CSV file or display the data in a CSV friendly format to allow easy comparison of metrics collected such as RSS, image size or startup time.

**Comment by aclement** [comment]
I'm making a first commit on this. I'm tweaking each build script to produce a summary.csv in the output folder, then the top level script pulls them together. The output is like this:

```
Graal: GraalVM Version 19.2.1 CE
Date,Sample,Image Build Time (ms), RSS Memory (M), Image Size (M), Startup Time (s), JVM Uptime (s)
20191220-1116,commandlinerunner,88866.06,29.9,48.7,0.03,0.033
```
I'll wait for feedback before rolling it out to all of the samples. I will also increase the sleep after starting the process before collecting the RSS because I think that sometimes gives me erratic RSS measurements, if you measure it before it has quite 'got going'.

**Comment by aclement** [comment]
This is complete in the 19.3 branch and will appear in master when we move it over. I've rolled it out to a number of samples, last few will be done as we confirm they are still working.  After running the samples from the project root there will be `samples-summary.csv` containing the results
