### ISSUE TITLE
Fix wip agent samples

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graal-native#78]
By leveraging what has been saved in the [`wip-agent` branch](https://github.com/spring-projects-experimental/spring-graal-native/tree/wip-agent), we should add [`springmvc-tomcat`](https://github.com/spring-projects-experimental/spring-graal-native/tree/wip-agent/spring-graal-native-samples/springmvc-tomcat/wip-agent) and [`webflux-netty`](https://github.com/spring-projects-experimental/spring-graal-native/tree/wip-agent/spring-graal-native-samples/webflux-netty/wip-agent) sample agent like the one in `commandlinerunner`.

**Comment by aclement** [comment]
Done. There are now `agent` subfolders for `springmvc-tomcat` and `webflux-netty`. I've merged the multiple scripts into just one build script in each case, much easier to reuse.  Note the webflux-netty one 'just works' whilst the springmvc-tomcat one still needs customization (the agent doesn't report everything) - some of this is fixed in 20.1 but we need to remember to push on them to fix the resource bundle problem as it will affect all the tomcat apps.
